#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tldextract
Version  : 2.2.2
Release  : 7
URL      : https://files.pythonhosted.org/packages/cc/57/86c3c69d3df6b13c4ca1b41f4c57ec39051d002953b3960c276ce321837f/tldextract-2.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/cc/57/86c3c69d3df6b13c4ca1b41f4c57ec39051d002953b3960c276ce321837f/tldextract-2.2.2.tar.gz
Summary  : Accurately separate the TLD from the registered domain and subdomains of a URL, using the Public Suffix List. By default, this includes the public ICANN TLDs and their exceptions. You can optionally support the Public Suffix List's private domains as well.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: tldextract-bin = %{version}-%{release}
Requires: tldextract-license = %{version}-%{release}
Requires: tldextract-python = %{version}-%{release}
Requires: tldextract-python3 = %{version}-%{release}
Requires: idna
Requires: requests
Requires: requests-file
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : idna
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : requests
BuildRequires : requests-file
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
`tldextract` accurately separates the gTLD or ccTLD (generic or country code
top-level domain) from the registered domain and subdomains of a URL.

    >>> import tldextract
    >>> tldextract.extract('http://forums.news.cnn.com/')
    ExtractResult(subdomain='forums.news', domain='cnn', suffix='com')
    >>> tldextract.extract('http://forums.bbc.co.uk/') # United Kingdom
    ExtractResult(subdomain='forums', domain='bbc', suffix='co.uk')
    >>> tldextract.extract('http://www.worldbank.org.kg/') # Kyrgyzstan
    ExtractResult(subdomain='www', domain='worldbank', suffix='org.kg')

`ExtractResult` is a namedtuple, so it's simple to access the parts you want.

    >>> ext = tldextract.extract('http://forums.bbc.co.uk')
    >>> (ext.subdomain, ext.domain, ext.suffix)
    ('forums', 'bbc', 'co.uk')
    >>> # rejoin subdomain and domain
    >>> '.'.join(ext[:2])
    'forums.bbc'
    >>> # a common alias
    >>> ext.registered_domain
    'bbc.co.uk'

By default, this package supports the public ICANN TLDs and their exceptions.
You can optionally support the Public Suffix List's private domains as well.

%package bin
Summary: bin components for the tldextract package.
Group: Binaries
Requires: tldextract-license = %{version}-%{release}

%description bin
bin components for the tldextract package.


%package license
Summary: license components for the tldextract package.
Group: Default

%description license
license components for the tldextract package.


%package python
Summary: python components for the tldextract package.
Group: Default
Requires: tldextract-python3 = %{version}-%{release}

%description python
python components for the tldextract package.


%package python3
Summary: python3 components for the tldextract package.
Group: Default
Requires: python3-core
Provides: pypi(tldextract)

%description python3
python3 components for the tldextract package.


%prep
%setup -q -n tldextract-2.2.2
cd %{_builddir}/tldextract-2.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582909683
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tldextract
cp %{_builddir}/tldextract-2.2.2/LICENSE %{buildroot}/usr/share/package-licenses/tldextract/3851396c2644b4fa80d9149413773ef03c690377
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tldextract

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tldextract/3851396c2644b4fa80d9149413773ef03c690377

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
